;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="UI.Color.Error",DevComment="")
+GameplayTagList=(Tag="UI.Color.Info",DevComment="")
+GameplayTagList=(Tag="UI.Color.Success",DevComment="")
+GameplayTagList=(Tag="UI.Color.Warning",DevComment="")
+GameplayTagList=(Tag="UI.Font.DefaultInGame",DevComment="")
+GameplayTagList=(Tag="UI.Icon.Banner",DevComment="")
+GameplayTagList=(Tag="UI.Icon.Ore",DevComment="")
+GameplayTagList=(Tag="UI.Icon.Wood",DevComment="")

